name: ${project.name}
version: ${project.version}
api-version: 1.13
main: ${project.groupId}.${project.artifactId}.${project.name}
description: ${project.description}
authors: [drives_a_ford]

commands:
  pcpreload:
    description: Reload the plugin config
    usage: /<command>
    permission: pcp.reload

permissions:
  pcp.reload:
    description: Allows reloading plugin
    default: op